### PR TITLE
added login capabilities as well as refactored some checkout code

### PR DESCRIPTION
**Pull request by musubipapi**
Added login abilities as shown here:
screenshot from 2019-02-26 19-41-35

### CODE REVIEW

**Comment by musubipapi** [comment]
plz merge!!!

**Comment by musubipapi** [comment]
merge me!!!!

**Review by hoysay — APPROVED** [review]
Looks good - showing the ingredients on "Add more" click is also a good idea.

**Comment by musubipapi** [comment]
Thanks fam!

**Comment by jonathanfung123** [comment]
potential feature we can add is to login with social media such as facebook or google mail.

**Pull request merged**
