### PR TITLE
refactored code

### PR DESCRIPTION
**Pull request by musubipapi**

### CODE REVIEW

**Comment by musubipapi** [comment]
refactored some code

**Review by hoysay — COMMENTED** [review]
Thanks for doing the refactoring! The code looks good to me, but would you be able to add some screenshots to the PR conversation so we can see any visual changes?

**Comment by jonathanfung123** [comment]
the new design looks really clean. there still seems to be a lot of bugs and errors that you need to flush out. fix bugs and then we can merge it in.

**Review by hoysay — APPROVED** [review]
LGTM - the data seems fine in index.js for now, but I'm not sure if we want to move it to another file/location in a future PR.

**Pull request merged**
